"""Minimal hardcoded evidence base for MVP1.

Only the first validation chart is covered deliberately. New signs are added only
after real-user feedback confirms the report format works.
"""

# ── Practical recommendations ─────────────────────────────────────────────────
# Keyed by (factor, placement). Merged across Sun + Moon + Ascendant at runtime.
# Each entry has: career, sport, recovery — lists of short Ukrainian strings.

PRACTICAL = {
    ("Sun", "Gemini"): {
        "career": [
            "Журналістика та медіа",
            "Навчання і коучинг",
            "Маркетинг і PR",
            "Переговори та продажі",
            "IT і аналітика даних",
            "Письмо та редагування",
        ],
        "sport": [
            "Теніс або бадмінтон",
            "Командні ігри (волейбол, баскетбол)",
            "Велосипед",
            "Танці",
            "Плавання",
        ],
        "recovery": [
            "Ведення щоденника або нотаток",
            "Прогулянка з подкастом або музикою",
            "Жива розмова з близькою людиною",
            "Новий короткий курс або книга",
        ],
    },
    ("Sun", "Aquarius"): {
        "career": [
            "Технології та IT",
            "Наукові дослідження",
            "Соціальні проєкти та НГО",
            "Дизайн та футуризм",
            "Журналістика та незалежні медіа",
        ],
        "sport": [
            "Велосипед або самокат",
            "Плавання",
            "Групові тренування з командою однодумців",
        ],
        "recovery": [
            "Час наодинці без соцмереж",
            "Творчий проєкт без дедлайну",
            "Прогулянка в незнайомому районі",
            "Документальне кіно або лекція TED",
        ],
    },
    ("Sun", "Taurus"): {
        "career": [
            "Фінанси та управління ресурсами",
            "Нерухомість та будівництво",
            "Кулінарія або гастрономія",
            "Дизайн та архітектура",
            "Музика або звукорежисура",
            "Агробізнес або екологія",
        ],
        "sport": [
            "Плавання",
            "Пілатес або йога",
            "Ходьба або трекінг у природі",
            "Силові тренування зі стабільним навантаженням",
        ],
        "recovery": [
            "Час на природі без телефону",
            "Смачна їжа або приготування страви",
            "Музика або масаж",
            "Довгий сон і повільний ранок",
        ],
    },
    ("Moon", "Capricorn"): {
        "career": [
            "Управління проєктами",
            "Фінанси та інвестиції",
            "Право та консалтинг",
            "Стратегічне планування",
            "Архітектура або інженерія",
        ],
        "sport": [
            "Скандинавська ходьба або трекінг",
            "Гімнастика або стретчинг",
            "Йога з акцентом на дисципліну",
            "Силові тренування за чітким планом",
        ],
        "recovery": [
            "Самотність у природі без плану",
            "Масаж або баня",
            "Мовчазна медитація або body scan",
        ],
    },
    ("Moon", "Taurus"): {
        "career": [
            "Фінанси та управління ресурсами",
            "Кулінарія або гастрономія",
            "Нерухомість та будівництво",
            "Музика або звукорежисура",
        ],
        "sport": [
            "Плавання",
            "Ходьба в природі",
            "Пілатес або йога",
        ],
        "recovery": [
            "Час у природі або саду",
            "Музика або масаж",
            "Повільний ранок без поспіху",
        ],
    },
    ("Ascendant", "Taurus"): {
        "career": [
            "Дизайн та архітектура",
            "Кулінарія та гастрономія",
            "Музика або звукорежисура",
            "Нерухомість та будівництво",
        ],
        "sport": [
            "Плавання",
            "Пілатес або стретчинг",
            "Ходьба або трекінг у природі",
            "Силові тренування зі стабільним навантаженням",
        ],
        "recovery": [
            "Час на природі без телефону",
            "Смачна їжа або приготування страви",
            "Музика або масаж",
            "Довгий сон і повільний ранок",
        ],
    },
    ("Ascendant", "Libra"): {
        "career": [
            "Дипломатія та медіація",
            "Право та арбітраж",
            "Дизайн та мода",
            "PR і комунікації",
            "Психологія та коучинг",
        ],
        "sport": [
            "Теніс або бадмінтон",
            "Танці (парні)",
            "Йога або пілатес",
            "Плавання",
        ],
        "recovery": [
            "Естетичне середовище: порядок і краса вдома",
            "Спілкування в гармонійній компанії",
            "Мистецтво або відвідування виставки",
        ],
    },
}

RULES = {
    ("Sun", "Gemini"): [
        {
            "id": "curiosity_and_connection",
            "title": "Потреба розуміти і поєднувати",
            "category": "identity",
            "confidence": 0.90,
            "statement": "Вам важливо розуміти, пояснювати та зв'язувати між собою людей і ідеї — це ваш природний спосіб орієнтуватися у світі.",
            "rule_id": "sun_gemini_curiosity",
            "weight": 0.90,
            "priority": 1,
        },
        {
            "id": "flexible_thinking",
            "title": "Гнучкість мислення",
            "category": "thinking",
            "confidence": 0.85,
            "statement": "Ви швидко перемикаєтесь між темами і бачите кілька варіантів там, де інші бачать один. Це сила, але вона ж ускладнює вибір.",
            "rule_id": "sun_gemini_flexible_thinking",
            "weight": 0.85,
            "priority": 1,
        },
        {
            "id": "many_starts_few_endings",
            "title": "Багато початків і мало завершень",
            "category": "stress_response",
            "confidence": 0.78,
            "statement": "Увага легко переходить на нове, поки попереднє ще не завершено. Глибина доступна, але потребує свідомого зусилля.",
            "rule_id": "sun_gemini_depth_vs_breadth",
            "weight": 0.78,
            "priority": 2,
        },
    ],
    ("Moon", "Capricorn"): [
        {
            "id": "emotional_restraint",
            "title": "Емоційна витримка як відповідальність",
            "category": "emotional_needs",
            "confidence": 0.88,
            "statement": "Ви тримаєте почуття під контролем і рідко показуєте, чого вам це коштує. Для вас емоційна стриманість — форма зрілості.",
            "rule_id": "moon_capricorn_restraint",
            "weight": 0.88,
            "priority": 1,
        },
        {
            "id": "emotional_distance",
            "title": "Дистанція, яку близькі читають як холод",
            "category": "relationships",
            "confidence": 0.80,
            "statement": "Самоконтроль захищає вас — і водночас тримає людей на відстані. Моменти, коли ви дозволяєте собі бути вразливим, зближують більше, ніж ваша сила.",
            "rule_id": "moon_capricorn_distance",
            "weight": 0.80,
            "priority": 2,
        },
        {
            "id": "accumulated_feelings",
            "title": "Відкладені почуття, що накопичуються",
            "category": "stress_response",
            "confidence": 0.74,
            "statement": "Почуття рідко виходять одразу — вони накопичуються роками. Вам може бути важко просто сказати меною важко без пояснень і плану дій.",
            "rule_id": "moon_capricorn_accumulated",
            "weight": 0.74,
            "priority": 2,
        },
    ],
    ("Ascendant", "Taurus"): [
        {
            "id": "calm_reliable_impression",
            "title": "Перше враження — спокій і надійність",
            "category": "communication",
            "confidence": 0.86,
            "statement": "Люди бачать у вас стійкість і рівновагу ще до того, як ближче познайомляться. Поруч із вами людям спокійно.",
            "rule_id": "asc_taurus_calm",
            "weight": 0.86,
            "priority": 1,
        },
        {
            "id": "practicality_valued",
            "title": "Цінність практичності",
            "category": "identity",
            "confidence": 0.79,
            "statement": "Вас цінують за здоровий глузд і вміння зробити реальне. Вам довіряють те, що потребує тривалості.",
            "rule_id": "asc_taurus_practical",
            "weight": 0.79,
            "priority": 2,
        },
        {
            "id": "perceived_slowness",
            "title": "Розважливість, яку сприймають як повільність",
            "category": "stress_response",
            "confidence": 0.68,
            "statement": "Ваша розважливість може бути прийнята за повільність або відсутність амбіцій — це рідко відповідає дійсності.",
            "rule_id": "asc_taurus_misread",
            "weight": 0.68,
            "priority": 3,
        },
    ],
    ("Sun", "Aquarius"): [
        {
            "id": "need_for_independence",
            "title": "Потреба у самостійності",
            "category": "identity",
            "confidence": 0.91,
            "statement": "Вам важливо зберігати свободу вибору та самостійно визначати свій напрямок.",
            "rule_id": "sun_aquarius_independence",
            "weight": 0.91,
            "priority": 1,
        },
        {
            "id": "independent_thinking",
            "title": "Незалежність мислення",
            "category": "thinking",
            "confidence": 0.84,
            "statement": "Ви схильні перевіряти усталені погляди й формувати власну позицію, а не автоматично погоджуватися з більшістю.",
            "rule_id": "sun_aquarius_independent_thinking",
            "weight": 0.84,
            "priority": 1,
        },
        {
            "id": "future_orientation",
            "title": "Орієнтація на нове",
            "category": "decision_making",
            "confidence": 0.76,
            "statement": "Вашу увагу можуть особливо привертати нові підходи, нестандартні рішення та можливості покращити звичний порядок.",
            "rule_id": "sun_aquarius_future_orientation",
            "weight": 0.76,
            "priority": 2,
        },
    ],
    ("Sun", "Taurus"): [
        {
            "id": "stability_and_groundedness",
            "title": "Стійкість як внутрішня цінність",
            "category": "identity",
            "confidence": 0.91,
            "statement": "Вам важливо мати тверду основу — у роботі, стосунках, побуті. Стабільність для вас не консерватизм, а умова, за якої ви можете повністю розкритися.",
            "rule_id": "sun_taurus_stability",
            "weight": 0.91,
            "priority": 1,
        },
        {
            "id": "persistence_over_speed",
            "title": "Сила, що бере не швидкістю, а витривалістю",
            "category": "thinking",
            "confidence": 0.87,
            "statement": "Ви рідко поспішаєте — але те, що берете в роботу, доводите до кінця. Там, де інші здаються через втому, ви продовжуєте. Це рідкісна якість.",
            "rule_id": "sun_taurus_persistence",
            "weight": 0.87,
            "priority": 1,
        },
        {
            "id": "resistance_to_change",
            "title": "Зміни потребують часу на внутрішню згоду",
            "category": "stress_response",
            "confidence": 0.79,
            "statement": "Різкі повороти і нав'язані зміни можуть викликати внутрішній опір — навіть якщо розумом ви розумієте їхню необхідність. Вам потрібен час, щоб внутрішньо погодитися.",
            "rule_id": "sun_taurus_resistance",
            "weight": 0.79,
            "priority": 2,
        },
        {
            "id": "sensory_connection",
            "title": "Глибокий зв'язок із матеріальним світом",
            "category": "decision_making",
            "confidence": 0.73,
            "statement": "Ви добре відчуваєте якість — у речах, людях, процесах. Довіряєте відчуттям і практичному досвіду більше, ніж абстрактним ідеям.",
            "rule_id": "sun_taurus_sensory",
            "weight": 0.73,
            "priority": 3,
        },
    ],
    ("Moon", "Taurus"): [
        {
            "id": "need_for_stability",
            "title": "Потреба у стабільності",
            "category": "emotional_needs",
            "confidence": 0.89,
            "statement": "Емоційне відчуття безпеки посилюється, коли життя передбачуване, а зміни відбуваються без зайвого поспіху.",
            "rule_id": "moon_taurus_stability",
            "weight": 0.89,
            "priority": 1,
        },
        {
            "id": "sensory_recovery",
            "title": "Відновлення через прості відчутні речі",
            "category": "stress_response",
            "confidence": 0.78,
            "statement": "Під час напруги вам може допомагати повернення до простих тілесних і побутових опор: спокійного ритму, комфорту та зрозумілої рутини.",
            "rule_id": "moon_taurus_sensory_recovery",
            "weight": 0.78,
            "priority": 2,
        },
        {
            "id": "slow_emotional_decisions",
            "title": "Потреба не поспішати з емоційними рішеннями",
            "category": "decision_making",
            "confidence": 0.74,
            "statement": "У питаннях, що зачіпають безпеку й близькі стосунки, вам може бути важливо мати час, щоб внутрішньо дозріти до рішення.",
            "rule_id": "moon_taurus_slow_decisions",
            "weight": 0.74,
            "priority": 2,
        },
    ],
    ("Ascendant", "Libra"): [
        {
            "id": "diplomatic_self_presentation",
            "title": "Дипломатична подача себе",
            "category": "communication",
            "confidence": 0.84,
            "statement": "У контакті з людьми вам природно шукати коректний тон, рівновагу та взаємну повагу.",
            "rule_id": "asc_libra_diplomacy",
            "weight": 0.84,
            "priority": 1,
        },
        {
            "id": "relationship_balance",
            "title": "Потреба у взаємності",
            "category": "relationships",
            "confidence": 0.80,
            "statement": "У взаєминах вам може бути особливо важливо відчувати взаємність, справедливість і готовність обох сторін враховувати одна одну.",
            "rule_id": "asc_libra_relationship_balance",
            "weight": 0.80,
            "priority": 1,
        },
        {
            "id": "conflict_delay",
            "title": "Схильність відкладати пряме зіткнення",
            "category": "stress_response",
            "confidence": 0.66,
            "statement": "Коли незгода загрожує порушити рівновагу, ви можете спершу пом'якшувати позицію або відкладати пряму розмову.",
            "rule_id": "asc_libra_conflict_delay",
            "weight": 0.66,
            "priority": 3,
        },
    ],
}
